New function "sendSis" for sending CSV files via SIS Import
KTH/canvas-api pull request #11
Opened 2019-08-15 07:37 UTC by exacs

2019-08-20 10:37 UTC, Delodax requested changes

2019-08-20 10:37 UTC, Delodax commented on README.md
> +const {body} = (await canvas.sendSis('/accounts/1/sis_import', 'enrollments.csv', {})
- A stray parenthesis before `await`.
- Endpoint should be `accounts/1/sis_imports`

2019-08-20 10:37 UTC, Delodax commented on index.js
> +    return got
What do you think about also here using our `canvasGot` object, e.g.:
```
return canvasGot
      .post({
        url: endpoint,
        baseUrl: apiUrl,
        body: form,
        json: false
      })
```

2019-08-21 06:42 UTC, exacs commented on README.md
> +const {body} = (await canvas.sendSis('/accounts/1/sis_import', 'enrollments.csv', {})
Nice catch!

2019-08-23 13:05 UTC, merged