Better testing
KTH/canvas-api pull request #9
Opened 2019-05-02 11:50 UTC by exacs

This PR replaces the old `proxyquire`-based tests (they mock the responses from "request-promise") with new `create-test-server`-based tests (now tests mock a fictional Canvas server)

This means that our tests do not mock `request-promise` anymore, so they are ready for a future where we stop using `request` and `request-promise`.

2019-05-03 13:14 UTC, exacs commented on index.js
> -        url = response.headers && getNextUrl(response.headers.link)
This is a fix when `headers` are present but `headers.link` not. Not strictly related to the `better-testing` branch

2019-05-15 11:00 UTC, Delodax requested changes
Everything looks like improvements. A lot cleaner and smooth than before.

2019-05-15 11:00 UTC, Delodax commented on test/index.js
> +    { base: server.url + '/', end: '/index' },
One pretty anal question/suggestion:

- Both creating strings by "addition" (+) and template literals is used - any particular strategy or randoms selection? I think it would be nice to use only one strategy - if there's no big plan I don't see 🤔

2019-05-15 11:12 UTC, Delodax commented on test/index.js
> +    { base: server.url + '/', end: '/index' },
This was aligned to only used literals :)

2019-05-15 11:12 UTC, Delodax approved these changes

2019-05-15 11:15 UTC, merged